CREATE TABLE person(
	Id int NULL DEFAULT NULL,
	FirstName VARCHAR(50) NULL DEFAULT NULL,
	LastName VARCHAR(50) NULL DEFAULT NULL,
	Address VARCHAR(50) NULL DEFAULT NULL,
	Gender VARCHAR(50) NULL DEFAULT NULL
)